trigger:
- master
- releases/*

jobs:
  - job: Test_Linux
    displayName: Run Tests on Linux
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        Node_v10:
          node_version: 10
        Node_v8:
          node_version: 8
        Node_v6:
          node_version: 6
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Test_Windows
    displayName: Run Tests on Windows
    pool:
      vmImage: "windows-2019"
    strategy:
      matrix:
        Node_v10:
          node_version: 10
        Node_v8:
          node_version: 8
        Node_v6:
          node_version: 6
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Test_MacOS
    displayName: Run Tests on MacOS
    pool:
      vmImage: "macOS-10.15"
    strategy:
      matrix:
        Node_v10:
          node_version: 10
        Node_v8:
          node_version: 8
        Node_v6:
          node_version: 6
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Notify_Coveralls
    displayName: Notify Coveralls that the parallel report is done
    pool:
      vmImage: "Ubuntu 16.04"
    dependsOn:
      - Test_Linux
      - Test_Windows
      - Test_MacOS
    steps:
      - script: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$BUILD_NAME&payload[status]=done"
        env:
          COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN_SECRET)
          BUILD_NAME: $(Build.BuildNumber)
