steps:
- script: npm i -g npm@$(npm_version)
  displayName: Use non-broken npm version $(npm_version)
  condition: ne(variables['npm_version'], '')

- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: Use Node $(node_version)

- script: npm install
  displayName: npm install

- script: npm test
  displayName: Run tests

- script: npm run coveralls
  displayName: Run coveralls
  env:
    COVERALLS_SERVICE_NAME: Azure Pipelines
    COVERALLS_SERVICE_NUMBER: $(Build.BuildNumber)
    COVERALLS_SERVICE_JOB_ID: $(Agent.OS)_$(node_version)
    COVERALLS_GIT_BRANCH: $(Build.SourceBranchName)
    COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN_SECRET)
    COVERALLS_PARALLEL: true
    CI_PULL_REQUEST: $(System.PullRequest.PullRequestNumber)

- script: npm run azure-pipelines
  displayName: Write tests to xml

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test.xunit'
  condition: succeededOrFailed()
